version: "2.1"
services:
  sdns:
    image: c1982/sdns
    container_name: sdns
    networks:
      - searxng
    restart: unless-stopped
    ports:
      - 53:53
      - 53:53/udp
      - 19510:8080
    volumes:
      - ./sdns.conf:/sdns.conf
networks:
  sdns:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: fe80:s::/64
